name: caddy
summary: Fast, multi-platform web server with automatic HTTPS.
description: |
  Caddy is a powerful, extensible platform to serve your sites, services, and
  apps, written in Go.
version: "v2.0.0"

base: core20
grade: devel
confinement: strict
epoch: 2

apps:
  caddy:
    command: bin/caddy
    plugs:
      - home
      - network-bind
    environment:
      XDG_DATA_HOME: $SNAP_USER_COMMON
      XDG_CONFIG_HOME: $SNAP_USER_COMMON

  deamon:
    command: bin/caddy run --resume
    daemon: simple
    plugs:
      - network-bind
    environment:
      XDG_DATA_HOME: $SNAP_COMMON
      XDG_CONFIG_HOME: $SNAP_COMMON

parts:
  caddy:
    build-packages:
      - build-essential
      - git
    build-snaps:
      - go
    plugin: nil
    override-build: |
      go get -u github.com/caddyserver/xcaddy/cmd/xcaddy
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      $(go env GOPATH)/bin/xcaddy build --output $SNAPCRAFT_PART_INSTALL/bin/caddy

